scanner_name: "Siemens Quadra"
simset_material: 18
average_doi: 0.7
scanner_radius: 41.0
num_rings: 320 #Real: 320, With module gaps: 323
axial_fov: 106
z_crystal_size: 0.32 #cm
transaxial_crystal_size: 0.32 #cm
crystal_thickness: 2 #cm
energy_resolution: 9
num_aa_bins: 399
num_td_bins: 520
min_energy_window: 435
max_energy_window: 585
coincidence_window: 4.7 #ns

numberOfSubsets: 7
numberOfIterations: 14
savingInterval: 7
analytical_att_correction: 0
stir_recons_att_corr: 0
analytic_scatt_corr_factor: 0.15
stir_scatt_corr_smoothing: 0
stir_scatt_simulation: 0
analytic_randoms_corr_factor: 0.2
stir_randoms_corr_smoothing: 0
recons_type: "OSEM3D" #Options: "FBP2D", "FBP3D", "OSEM2D", "OSEM3D"
inter_iteration_filter: 0
subiteration_interval: 4
x_dir_filter_FWHM: 1.5
y_dir_filter_FWHM: 1.5
z_dir_filter_FWHM: 3
psf_value: 0
add_noise: 0

max_segment: 85 #Reduced protocol: 85; Full protocol: 319 or 322
zoomFactor: 1
xyOutputSize: 220
zOutputSize: 645
zOutputVoxelSize: 1.65

attenuation_mode: 0 #0: no attenuation, 1: attenuation with SimSET, 2: attenuation with STIR
